In [1]:
import pandas as pd

In [2]:
# 1. Version
pd.__version__

'2.2.2'

In [6]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv')

In [9]:
# 2. No of records
df.shape[0]

2160

In [10]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [14]:
# 3. No of brands
df.Brand.nunique()

27

In [15]:
# 4. No of columns with missing values
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [16]:
# 5. Maximum final price of dell notebook
df[df['Brand'] == 'Dell']['Final Price'].max()

3936.0

In [27]:
# 6.1 Median value of Screen
screenMedian = df['Screen'].median()
screenMedian

15.6

In [28]:
# 6.2 Mode value of Screen
screenMode = df['Screen'].mode()
screenMode

0    15.6
Name: Screen, dtype: float64

In [29]:
# 6.3 Fill null value of Screen with its mode
df['Screen'] = df['Screen'].fillna(screenMode)

In [30]:
# 6.4 New Median value
df['Screen'].median()

15.6

In [31]:
# 7.1 Get all Innjoo laptops
df = df[df['Brand'] == 'Innjoo']

In [34]:
# 7.2 Get Selected Columns
df = df[['RAM', 'Storage', 'Screen']]

In [37]:
# 7.3 Numpy array
X = df.values
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [38]:
# 7.4 Multiplt transpose X with X
XTX = X.T.dot(X)
XTX

In [46]:
# 7.5 Inverse of XTX
import numpy as np
XTXinv = np.linalg.inv(XTX)
XTXinv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [47]:
# 7.6 Create an array Y
y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [49]:
# 7.7
w = XTXinv.dot(X.T).dot(y)
w

array([45.58076606,  0.42783519, 45.29127938])

In [50]:
# 7.8
w.sum()

91.29988062995805